import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Repo root (one up from web/) - the project's .env and package.json live there.
const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

// One id per build: version + a base36 timestamp. Computed ONCE at config load
// so the client constant and dist/build-id.txt are byte-identical.
const buildId = `${pkg.version}+${Date.now().toString(36)}`;

// Dev server on :5173 proxies /api/* to the oddspro API server (:3001).
export default defineConfig(({ command, mode }) => {
    // Only VITE_-prefixed vars (loadEnv's default) are read from the root .env,
    // so DB/API secrets are never touched. These are client-only branding
    // values baked into the build (like VITE_API_TOKEN, which must match the
    // server's API_TOKEN - both are set in .env before `npm run build:web`).
    const env = loadEnv(mode, repoRoot);
    const title = `${env.VITE_APP_NAME || 'Odds Pro'} v${pkg.version}`;
    const gaId = env.VITE_GA_ID;

    return {
        // Client-readable build constant: the package version, surfaced as a
        // tiny greyed label in the toolbar (E4). Baked in at build time.
        define: {
            __APP_VERSION__: JSON.stringify(pkg.version),
            // Build-unique id for deploy detection. The VERSION alone is not
            // enough - two builds of the same version produce different hashed
            // assets, so a redeploy without a version bump would leave every
            // open tab silently stale. The same string is written to
            // dist/build-id.txt below, which is what the server serves, so the
            // two sides are generated by ONE build and cannot disagree.
            __BUILD_ID__: JSON.stringify(buildId),
        },
        plugins: [
            react(),
            tailwindcss(),
            {
                // Emit the build id beside the bundle. The server reads this
                // file and returns it on /api/refresh; the client compares it
                // to its baked-in __BUILD_ID__. Deliberately a plain text file:
                // no parsing, and an absent one (dev, or a backend deployed
                // without a frontend build) simply disables the check.
                name: 'oddspro-build-id',
                apply: 'build',
                writeBundle(options) {
                    const dir = options.dir || 'dist';
                    writeFileSync(`${dir}/build-id.txt`, buildId, 'utf8');
                },
            },
            {
                // Bake the env-driven <title> into index.html, and inject the
                // Google Analytics snippet for PRODUCTION builds only (never the
                // dev server) so local traffic stays out of analytics.
                name: 'oddspro-html-env',
                transformIndexHtml(html) {
                    html = html.replace(/<title>[\s\S]*?<\/title>/, `<title>${title}</title>`);
                    if (command === 'build' && gaId) {
                        const ga = `<script async src="https://www.googletagmanager.com/gtag/js?id=${gaId}"></script>\n`
                            + `    <script>\n`
                            + `        window.dataLayer = window.dataLayer || [];\n`
                            + `        function gtag() { dataLayer.push(arguments); }\n`
                            + `        gtag('js', new Date());\n`
                            + `        gtag('config', '${gaId}');\n`
                            + `    </script>\n`;
                        html = html.replace('</head>', `    ${ga}</head>`);
                    }
                    return html;
                },
            },
        ],
        server: {
            port: 5173,
            proxy: { '/api': 'http://localhost:3001' },
            // The table imports the shared pure scorer from ../src/db/ (one
            // magic-sort implementation server + client); the dev server's fs
            // guard must allow reads above web/. Build needs no config - Rollup
            // follows relative imports anywhere.
            fs: { allow: ['..'] },
        },
    };
});
